---
- name: Configure Docker on EC2 Instances
  hosts: ansiblegroup
  become: true
  connection: ssh

  tasks:
    - name: Updating apt
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start & Enable Docker Service
      service:
        name: docker
        state: started
        enabled: true

    - name: Deploy Docker Container
      command: docker run -itd -p 8084:8082 priyan263/priyanka-health-care
