- name: Deploy Healthcare App on EC2
  hosts: ansiblegroup
  become: true

  tasks:
    - name: Install required packages
      apt:
        name:
          - docker.io
          - python3-pip
        state: present
        update_cache: yes

    - name: Install Docker Python SDK (required for docker_container module)
      pip:
        name: docker

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Stop and remove existing container (if any)
      docker_container:
        name: priyanka-health-care
        state: absent

    - name: Deploy new Healthcare container
      docker_container:
        name: priyanka-health-care
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        restart_policy: always
        published_ports:
          - "8084:8082"
