---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
        - name: Healthcare
          image: priyan263/medicure:1.0
          ports:
            - containerPort: 8084
          env:
            - name: PORT
              value: "8084"
---
apiVersion: v1
kind: Service
metadata:
  name: medicure
spec:
  type: NodePort
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app: medicure
