---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: priyanka-health-care
spec:
  replicas: 1
  selector:
    matchLabels:
      app: priyanka-health-care
  template:
    metadata:
      labels:
        app: priyanka-health-care
    spec:
      containers:
        - name: Healthcare
          image: priyan263/priyanka-health-care
          ports:
            - containerPort: 8084
          env:
            - name: PORT
              value: "8084"
---
apiVersion: v1
kind: Service
metadata:
  name: priyanka-health-care
spec:
  type: NodePort
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app: priyanka-health-care
